name: Logos
main: io.github.bobthecookie.logos.Logos
version: 0.1

commands:
  help:
    description: Displays all Logos commands
    usage: /<command>
    permission: logos.basic
    permission-message: You don't have permission
  recipe:
    description: Displays the recipe for <book>
    usage: /<command> <book>
    permission: logos.basic
    permission-message: You don't have permission
